# These are supported funding model platforms

github: [ikimukti, himastatut-admin]
patreon: himastat_ut
open_collective: himastat_ut
ko_fi: himastat_ut
liberapay: himastat_ut
issuehunt: himastat-ut
buy_me_a_coffee: himastat_ut
thanks_dev: gh/himastatut-admin
